---
title: "sbert_draft"
format: html
---

```{r}
library(tidyverse)
library(Rtsne)
library(here)

source(here("data_helpers.R"))
source(here("theme.R"))
```

```{r}
DATA_LOC = here("../refbank-import/harmonized_data")
all_dirs <- list.dirs(DATA_LOC, full.names = FALSE) |> 
  stri_remove_empty()
all_trials <- map(all_dirs, \(d) get_trials_full(DATA_LOC, d)) |>
  list_rbind() |> 
  mutate(option_size = option_set |> 
           str_split(";") |> 
           lengths()) |> 
  filter(option_size != 1)
all_embeds <- map(all_dirs, \(d) get_tbl(DATA_LOC, d, "embeddings")) |>
  list_rbind() 
```

```{r}
all_embeds_fix <- all_embeds |> 
  mutate(embeddings = map(embeddings, \(e) {
    e |> 
      str_split("[\\[\\](\\n) ]") |> 
      map(\(x) x[x != ""] |> as.numeric())
  }))

embed_mat <- all_embeds_fix$embeddings |> 
  unlist(use.names = FALSE) |> 
  matrix(ncol = 384, byrow = TRUE)

embed_tsne <- embed_mat |> 
  Rtsne(verbose = TRUE, check_duplicates = FALSE) |> 
  (\(x) x$Y)() |>
  as_tibble(.name_repair = "universal") |> 
  setNames(c("x", "y")) |> 
  cbind(all_embeds |> select(-text, -embeddings)) |> 
  left_join(all_trials, by = join_by(paper_id, game_id, trial_id))
```

```{r}
ggplot(embed_tsne |> 
         filter(target %in% c("A", "B", "C", "D", "E", "F",
                              "G", "H", "I", "J", "K", "L")), 
       aes(x = x, y = y, 
           col = as.factor(target))) +
  geom_point(alpha = .1) +
  labs(x = "t-SNE dimension 1",
       y = "t-SNE dimension 2",
       color = "Target") +
  theme(legend.position = "none")
```


